<?php
if($this->name){
    echo 'Привіт ' . $this->name;
}
?>

<table>
    <tr>
        <td>Назва статті</td>
        <td>Опис</td>
        <td>Текст статті</td>

    </tr>

<?php

    foreach($this->list as $value){

        echo "<tr>
                <td>{$value['name']}</td>
                <td>{$value['short_text']}</td>
                <td>{$value['full_text']}</td>
              </tr>";

    }

?>

</table>

