<?php
if($this->name){
    echo 'Привіт ' . $this->name;
}
?>

<table>
    <tr>
        <td>Назва статті</td>
        <td>Опис</td>
        <td>Перейти до статті</td>
        <td>Редагувати</td>

    </tr>

<?php

    foreach($this->list as $value){

        echo "<tr>
                <td>{$value['name']}</td>
                <td>{$value['short_text']}</td>
                <td><a href='/article/id/{$value['id']}'>Show</a></td>
                <td><a href='/article/edit/{$value['id']}'>Edit</a></td>
              </tr>";

    }

?>

</table>

