<html>
<head>
    <title>zf layout</title>
    <?php   echo $this->jQuery(); ?>
    <?php   $this->headScript()->appendFile('/js/bootstrap.js');?>
    <?php   $this->headScript()->appendFile('/js/jquery.js');?>

    <?php   $this->headLink()->appendStylesheet('/css/bootstrap.css');?>
    <?php   $this->headLink()->appendStylesheet('/css/bootstrap-responsive.css');?>
    <?php   $this->headLink()->appendStylesheet('/css/style.css');?>

    <?php echo $this->headScript();?>
    <?php echo $this->headLink();?>
</head>
<body>
<div class="row-fluid">
    <div class="span12">
        <div class="pagination-centered"><h1>Zend Training</h1></div>
        <div class="navbar navbar-inverse">
            <div class="navbar-inner">
                <div class="container">
                    <ul class="nav navigation">
                        <?php

                            echo $this->navigation()
                                      ->menu()
                                      ->setMaxDepth(0)
                                      ->render(new Maslov_Navigation($this->navigation()->findAllBy('tag','topMenu',true)));
                        ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div class="span3"></div>
            <div class="span6 trash">
                <?php echo $this->layout()->content;?>
            </div>
            <div class="span3"></div>
        </div>
    </div>
    <div class="row-fluid">
        <div class="span12">
            <div class="hero-unit">
                <h1>Fuck off</h1>
                <p></p>
                <p>
                    <a class="btn btn-primary btn-large" href="http://zend-frameworks.com" target="_blank">
                        Learn more
                    </a>
                </p>
            </div>
        </div>
    </div>
</div>
</body>
</html>