<html>
<head>
    <title>zf layout</title>
    <?php   echo $this->jQuery(); ?>
    <?php   $this->headScript()->appendFile('/js/bootstrap.js');?>

    <?php   $this->headLink()->appendStylesheet('/css/bootstrap.css');?>
    <?php   $this->headLink()->appendStylesheet('/css/bootstrap-responsive.css');?>

    <?php echo $this->headScript();?>
    <?php echo $this->headLink();?>
</head>
<body>
<a href="/user/registration">Реєстрація</a>
<a href="/index/index">Головна</a>
<a href="/user/login">Логін</a>
<a href="/article/new">Додати статтю</a>
<a href="/article/list">Список статей</a>
<?php echo $this->layout()->content;?>
</body>
</html>