<table>
    <tr>
        <td>ID користувача</td>
        <td>Ім'я користувача</td>
        <td>Прізвище користувача</td>
        <td>Електронна пошта</td>
        <td>Роль</td>

    </tr>

<?php
foreach($this->list as $value){

    echo "<tr>
                <td>{$value['id']}</td>
                <td>{$value['first_name']}</td>
                <td>{$value['last_name']}</td>
                <td>{$value['email']}</td>
                <td>{$value['role']}</td>
              </tr>";

}
?>